api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "shipping-discount"
type = "function"
uid = "9819460b-f956-a05b-6f7a-1fcb44ef82e108434317"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.shipping-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
